{ self,  unstable, ... }: {
  (with unstable; [
      fetch-scm
      fetchutils
      afetch
      hayabusa
      owofetch
      maxfetch
      bunnyfetch
      yafetch
      leaf
      nitch
      screenfetch
      disfetch
      bfetch
      nerdfetch
      fet-sh
      profetch
      macchina
      uwufetch
      starfetch
      ramfetch
      pridefetch
      pfetch
      pfetch-rs
      neofetch
      hyfetch
      freshfetch
      fastfetch
    ]);
  }
