default:
	just --list

switch:
	sudo nixos-rebuild switch --flake .

prune: prune-nix prune-docker

prune-nix:
	sudo nix-collect-garbage -d
	sudo nix-collect-garbage
	nix-store --optimise

prune-docker:
	podman container prune 
	podman image prune -a --external

update-flake:
	nix flake update

update: update-flake switch
